Add QATask Toggle
yismailuofa/kraken-frontend pull request #133
Opened 2024-03-21 06:01 UTC by yismailuofa

https://github.com/yismailuofa/kraken-frontend/assets/59630201/31ffd385-3b7f-45c4-b508-1c2c98517466

maybe this completes #95 ? Not sure what how much more work we need on this screen or if we offload the status to another screen?

cc @ElenaArnold @acl-24

2024-03-21 18:03 UTC, ElenaArnold commented
> Screen.Recording.2024-03-20.at.11.59.35.PM.mov 
> maybe this completes #95 ? Not sure what how much more work we need on this screen or if we offload the status to another screen?
> 
> cc @ElenaArnold @acl-24

I think that works for displaying QA vs alpha dependencies.

I was also thinking we could maybe also have a filter so that you can see all vs. completed vs. not completed tasks/milestones/qa tasks and maybe we could display some percentage for the project completion based on the toggle (i.e. when QA task toggle is off display (num_tasks_completed / total_tasks) and when the toggle is on (num_tasks_completed + num_qa_tasks_completed) / (total_tasks + total_qa_tasks). What do you think?

2024-03-21 20:12 UTC, yismailuofa commented
> > Screen.Recording.2024-03-20.at.11.59.35.PM.mov
> > maybe this completes #95 ? Not sure what how much more work we need on this screen or if we offload the status to another screen?
> > cc @ElenaArnold @acl-24
> 
> I think that works for displaying QA vs alpha dependencies.
> 
> I was also thinking we could maybe also have a filter so that you can see all vs. completed vs. not completed tasks/milestones/qa tasks and maybe we could display some percentage for the project completion based on the toggle (i.e. when QA task toggle is off display (num_tasks_completed / total_tasks) which is labeled as 'Alpha Completeness' and when the toggle is on (num_tasks_completed + num_qa_tasks_completed) / (total_tasks + total_qa_tasks), which is labeled as 'QA Completeness'. What do you think?

I think this makes sense, the only thing I'd change is that QA completeness is the same formula as alpha completeness with the difference being that the condition for "completeness" in QA completeness requires both task and qa task to be done.

2024-03-21 21:46 UTC, ElenaArnold requested changes
Looks really good! I think it just needs some error checking for when tasks completed = 0 so it displays something other than NAN. For example in a project that has no tasks all the values are NAN.
![image](https://github.com/yismailuofa/kraken-frontend/assets/114539416/17776ef0-82af-4495-9cbb-e7e3e7a2b744)

2024-03-22 04:54 UTC, ElenaArnold approved these changes

2024-03-22 05:30 UTC, merged